# Generated by Django 3.1 on 2020-08-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='did',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
