# Generated by Django 3.1 on 2020-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager', '0002_auto_20200829_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
    ]
